### ISSUE TITLE
question about greeks.json

### ISSUE THREAD

**Issue by seven-two-eight** [konn/vscode-generic-input-method#3]
As an Agda user, just curious why [greeks.json](https://github.com/konn/catex/blob/master/defaults/greeks.json) is not included by default?

**Comment by konn** [comment]
Ah, I removed it from generic-input-method just because it seemed that it is latex-specific.
But, yes, right! it must be useful for theorem provers. I will consider duplicate it to generic-input-method.

**Comment by seven-two-eight** [comment]
Good to know! Closing because there isn't really any issue.

I think your method is the way to go for input Unicode symbols.
I would argue [language-agda](https://github.com/j-mueller/language-agda) should integrate your extension instead of using hard-coded snippets. 

Thanks for the great work!

**Comment by konn** [comment]
I've just released new versions of `generic-input-method` and `catex`, with `defaults/greeks.json` backported to gim.

**Comment by seven-two-eight** [comment]
Change confirmed! 

I'm not sure about the intended usage. But for my usage in Agda, I also did a quick replace, so the body is the Greek letter, instead of letter name.

from
```json
  {
    "label": "a",
    "body": "alpha",
    "description": "α"
  },
  {
    "label": "b",
    "body": "beta",
    "description": "β"
  },
  {
    "label": "g",
    "body": "gamma",
    "description": "γ"
  },
...
```
to
```json
  {
    "label": "a",
    "body": "α",
    "description": "α"
  },
  {
    "label": "b",
    "body": "β",
    "description": "β"
  },
  {
    "label": "g",
    "body": "γ",
    "description": "γ"
  },
  {
    "label": "G",
    "body": "Γ",
    "description": "Γ"
  },
...
```

**Comment by konn** [comment]
Aha, right. It might be more desirable to have another dedicated package for Unicode math symbols.
