### ISSUE TITLE
v not replacing with unicode Vel symbol

### ISSUE THREAD

**Issue by Ifrit-Fire** [konn/vscode-generic-input-method#4]
Expecting **v** to insert the Vel symbol **∨**.  However it's just inserting the normal ascii **v**.

**Comment by konn** [comment]
Well, it's not actually a bug. But I will add that symbol in near future.
Meanwhile, as is stated in README, you can modify your `settings.json` so that you can input ∨ with `\v`:

```jsonc
"generic-input-methods.input-methods": [
    {
      "name": "Unicode Math",
      "commandName": "text.math",
      "languages": ["markdown", "redtt"], // any languages you need...
      "triggers": ["\\"],
      "dictionary": [
        "defaults/math.json", // default dictionary to inheret
        { "label": "v", body: "∨" }
      ]
    }
  ]
```

**Comment by Ifrit-Fire** [comment]
Gotcha.  Thank you for the response.  Closing for "Working as intended".
